# Setup
title:        transparent Software-Defined Exchange (tSDX)
tagline:      SDN for Optical Networks
baseurl:      ""
paginate:     1
url:          https://github.com/UA-Agile-Cloud/tSDX

# About/contact
author:
  name:       TOAN
  url:        http://osn.webhost.uits.arizona.edu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
